# Generated by Django 3.1.1 on 2020-09-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True, verbose_name='Номер столика')),
                ('places', models.SmallIntegerField(verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время резерва')),
                ('end_time', models.DateTimeField(verbose_name='Окончание резерва')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон клиента')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='reserv_api.table')),
            ],
            options={
                'verbose_name': 'Резерв столика',
                'verbose_name_plural': 'Резервы столиков',
            },
        ),
    ]
